// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyZxSB5SL74DQ1CUtC_VOBApl65Vy1Hqk',
    appId: '1:564691686377:web:626c4ce3b82aeef7ca3178',
    messagingSenderId: '564691686377',
    projectId: 'zoomclone-c5496',
    authDomain: 'zoomclone-c5496.firebaseapp.com',
    databaseURL: 'https://zoomclone-c5496-default-rtdb.firebaseio.com',
    storageBucket: 'zoomclone-c5496.firebasestorage.app',
    measurementId: 'G-1Q09LC4GNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUWdhVK6J8MOKtJy4xkye2R1ZE-U8FmuA',
    appId: '1:564691686377:android:45363a08d7ae1782ca3178',
    messagingSenderId: '564691686377',
    projectId: 'zoomclone-c5496',
    databaseURL: 'https://zoomclone-c5496-default-rtdb.firebaseio.com',
    storageBucket: 'zoomclone-c5496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ77nqAnkhTOlKswgkBR0H3lu5yMSWNxg',
    appId: '1:564691686377:ios:10b2df001edbf330ca3178',
    messagingSenderId: '564691686377',
    projectId: 'zoomclone-c5496',
    databaseURL: 'https://zoomclone-c5496-default-rtdb.firebaseio.com',
    storageBucket: 'zoomclone-c5496.firebasestorage.app',
    iosBundleId: 'com.example.myzoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ77nqAnkhTOlKswgkBR0H3lu5yMSWNxg',
    appId: '1:564691686377:ios:10b2df001edbf330ca3178',
    messagingSenderId: '564691686377',
    projectId: 'zoomclone-c5496',
    databaseURL: 'https://zoomclone-c5496-default-rtdb.firebaseio.com',
    storageBucket: 'zoomclone-c5496.firebasestorage.app',
    iosBundleId: 'com.example.myzoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyZxSB5SL74DQ1CUtC_VOBApl65Vy1Hqk',
    appId: '1:564691686377:web:70f78ac6a05b5fd2ca3178',
    messagingSenderId: '564691686377',
    projectId: 'zoomclone-c5496',
    authDomain: 'zoomclone-c5496.firebaseapp.com',
    databaseURL: 'https://zoomclone-c5496-default-rtdb.firebaseio.com',
    storageBucket: 'zoomclone-c5496.firebasestorage.app',
    measurementId: 'G-6P54KP672D',
  );

}